### ISSUE TITLE
no more leveldb?

### ISSUE THREAD

**Issue by ungoldman** [chelm/geomash#2]
Hey @chelm, noticed that you replaced LevelDB with Redis in your last release. The description of the module is still "a module that build geohash aggregations in levelDB" -- that probably needs changing or the purpose of the module needs reframing.

**Comment by chelm** [comment]
ahh thanks. I changed the readme but not the repo description. Re: redis. It supports both an in-memory and redis backed cache. The reason leveldb didnt fit the bill was because I needed to run these aggregations from a different machines in parallel...and redis is actually great for this type of thing.

**Comment by chelm** [comment]
fixed and updated readme with badges
